#! /bin/sh -e

patch -p1 < allow-llvm30.patch

./configure --prefix=/usr \
    --enable-gallium-llvm \
    --enable-gallium-egl \
    --enable-glx-tls \
    --with-driver=dri \
    --with-dri-drivers=i810,i915,i965,mach64,mga,r128,r200,r300,r600,radeon,savage,sis,tdfx,unichrome,swrast \
    --enable-xcb \
    --disable-glut \
    --enable-gles1 \
    --enable-gles2 \
    --enable-egl \
    --enable-texture-float \
    --enable-shared-dricore \
    CXXFLAGS="-std=c++11"

make
make DESTDIR="$1" install
